language: java
install:
- sudo apt install default-jre
- gradle assemble
os: linux
script: 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests;fi'
branches:
  only:
    - main

jobs:
  include:
  - stage: Checkout
  - stage: Test
    script: "./gradlew test"
  - stage: Build
    script:
    - "./gradlew build"
    - "./gradlew run"
  - stage: Deploy
    deploy:
      skip_cleanup: true 
      provider: heroku
      api_key:
        secure: ly5LgjHUbMSbTKp+17fY5dgY3Lq4QlKYsLUYOmXtexFKsU02XQdDZJQkQkbrs8yzabDbYC5gVOId94Hzxxcw6lkbr3Kdcex1PsktTUAmV97puD6/ArBGExjoWXsIvZo5I2ZciXnFOSw8kQPtMiNtwSHpkHSFkRvSqIPCN7sTa7T5C3Sv7YPaOWtBS6L3rQxixxOU0EwWq0Si2TirVDCxTKXdEWvt4dXb9Y8aXyynu0Q7ILT88i+FbK0Bt9BJmrS6Li2Uy8pyo1xJjhPeaI0JrKPMSszMVBYoKIg2tDG+bP20pTZtrL0VHcWc3wpDwgFJUOAZVpR/iKR71xt7LoHdBRMUrrG/NeP0X+FZocAJFOt6RDA9oZ6ep2CrMYVr4r2xjRRm0844QbXJN5ONnl1aDJ02qES/K/Lz3S36RFODGCKB4vYm1boPu7V8XpU/sas3koCHNngLRWOp6yFqVmu1kYTh1v0QrcKrYRiB989m6ijTeAyDfQHbK6okWgrfbFqxWz1Ts5cieNFEWtVH/toM2aAGYB9J7/3fzXYYKA77gzN2AzvXKEj7qqQFLUcEQdfkYX+M5ReOkRbj8UUJyeT6YOB6b+ngSAEn2d+9WEFUFj1Y3P6PHLexlPEiElnv3l9pjg2u0jadma2SOyqkhbKFb4AvHPmi45cUYM/p0nEuX1I=
      app: ci-me-please-app
      on:
        repo: crmejiam/ci-me-please
        all_branches: true
notifications:
  slack:
    secure: aR8fi2vtSuFQ0uDeC7iQzUkuXosXGuYaEB23cBtqkRrCYfm7r6I5T8Gygd7C8kZukvYiiuZd2MdWn7DAyQWW+ptpwQwevzUeUt8HuQb3YT3YznZAiDjmLkEnTBk6l0glvR519SVNlIfu8ocGGY1fk+TdCSoUs/deR/F01idUBaqYTfQRsvWngzpAcc43hDyMpB0eqYvfKVYkt+gJY10Jj/o4UluW7p86MlxhZWmVybqGQrIsikq2BDTuiZcQbYxSPruArTt+D4/33qXjFPpM2+BweLSAhvSdny8iaERa2eLu86rK2wcJbAKoWFQbXnooAAJwS/G08zGJFjCGKSPAHdEgmqSWx0wHgDkq/rtaf0P5DQpjA98OWlNrDoxXH+2czLDj0Zfg8Vr+uJ6WXv/QqN7KGRcyGpPzeqYTEIrLXddT0vWQnKppKPpa7vBz0xRaCL2m1phESsycuI87v1Q+2QZXYJWNIqbAMQYJc/lingWiKUDOGpYur9kG+BRaDVCNslBuoypkoZ3+L05R5iGBJnk2eVhZFUahWCwhw/dcn3+8DvJsbS1Noftd5WslaYes56sjgdf/of1VDwKMLXWCFCxBld687tdL7ThUJIhi5KZEdd8RMkNtSfZiK+zOykYSRyBS8jXHtm1j9Uin/toHOLqjysHE+yalBcPB5tsnSa8=
  email: false
services:
- docker
after_success:
- echo 'Yay! Success!'
after_failure:
- echo 'Damn... Failure'
