language: java
install:
- sudo apt install default-jre
- gradle assemble
os: linux
script: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests;
  fi
env:
  global:
  - secure: cD9Zj2QJg2lHpGiS5nhjmzRlTYizwSToFqQvvyEp0ThPEs/7mJQ99Qby4V+lEjx8pqycs9cJUqXVnR8dv24ybDRx5N85vQtmB/69wdRlSCJFOw2o9RtmiHKhoBr9r/1GC35Vt7Bze7CqFcOhUG0n7TCcRwR6MZ3KDGFaC4HMTbhQbf9C92lquMBRBDlrZjXIgUQg5at2sMlDkX6qyUYQk0ATmJshIXAs6tbKPztoH2sDaiq2z2NjJKsFfsRlPKnDC9SVPuWwPRalu+gI4+aIu0E5K1ygn4TnRS1aBn7ScxiVo6qlTuZ1gctuBb4XpEORPInCxofNHT8LZE+up9HO56UEq0Hw7ybXneiRhIzl/ng62yUgAZGOqq3KMD2EXYHFhdvY6AmsKgyaxUCobQMSD0+SW5dsymF90z+d7hDQwycFqA5dT0bRIynhgZbpMOQgOG7a8q0LO1m+BvPuq5sGBPY4a39CWn/qoZ4LY5kSY6odVHAZFp7XkztvHXRkQoOQ0vlkfxJ+K/N+4idvw4PP96G7JNDDxl7wxOUcwEPOI0WeUcgAjhDq4Od2Vdc7i20LgUfTCc8FMfcWVghrzLHRCLaRqDCA2s3TYvC4SosuRhZDHkUphxlw9mn9QmXh6IgsHK0j+QAEccxiuiKdCo9RSQK9icOMsfYlOVqwyRoSqxE=
  - secure: P5V645ZXSwOw1hpCOZSwspvf4zS2GtLUrHP1dd7pyd2ax5cjdJMOq90MwQuOsYTBsheW3yIH2hbpkMK7BZU7iStz97I5OZxlLsXfr3+fgShCJK9J34aplGmpI0+t5FmDZN+gc4gfqSBVT+lADet7wBx8kZ+qt500CEmAYqbd3TDWUHgzKjg66UaCNLC//WHYLp2qRtZIE+eZzQRT3KHn9ZR1xOXdnngSXoV/ppgTz6D759aZ7a4QbXRFG+VMm9a35COv6o+9YYT7uriTeHAJG0tW96zsHPPYbFdI0FAfQQ7K2Ioz6x1argtVZ4bBlyXE27+Smb5b07OaFdnN2t9FByoa/D4YfmTPWfi8MxtD3goxBrhBCq2VwILMaLYcmqQI0PH7gfrNYnoRIuh0Dmu+3uefqfX5nPOd0EM7j/igeattW+SPdFFs3dUIf0Uzsw2+cWx4EoUx5smTR7lR6bcN2AvexpJcA9yA1khGU3RpV84IgYjSxrRHuRwP06n79RGTCzbQCvLnUJY0eSOwM/vOkG9gFh/kty+r1FQum8V3sEtOan8SqRApIqy7LSMO/kqybNkrre+d2aonJvCjODlAauPoPhdnO26EHC+mLXQcleyCYhEyTyqTAi542OJ3VkcNBFadw3FLl//IQhIN9Kb/p3lMrwBOZ+Rep/y8U53L7nM=


jobs:
  include:
  - stage: Checkout
  - stage: Test
    script: "./gradlew test"
  - stage: Build
    script:
    - "./gradlew build"
    - "./gradlew run"
  - stage: Deploy
    deploy:
      provider: heroku
      api_key:
        secure: S7S1nsObm/CJzUdrtxA0nxbBVMIDVddD3JMVlz1bXNRPdEIG3HdtaEGMcsQl6RwWzQa/dRBO63PowPMjEDIJSyExS7dMCeyxAmNsakWL5x7QU/b2gAuG2BblwdOEafDl3ZuhpHRQTd7S45Sq2XsfHYD7mTXBA2R5VwOqEUp+rOKdnW3pzGN29jz+PgqfqbdpeaKdyo4+PQTMhXJAu6XIurl6RHnvMx/Mv7gVBRErWGJm1EO9znEEpJLZhdAobcugKGTIg2pmHoju3VMewy5l1nIgI1mQiDgK2YYzxi7YJA7nWFUwBEsom/P6tQd2xi0AVAaFf1JfJCB8w7KvF0A4d+kdbPOyKg0djgsEGLQfjDJfX5QBI4P6HmCQuxRFeCHpcM5l8Uhildpitmh/0puWfeVfpGwTCHsilXe7NZtXtR4PpPbkec9im/mFYugLnBjIkc3R0vkONoRShg4xBx5oRShZMM6uU4+M9Ray6pDGm2u6y10Q19WmBKaWwbjWxKRLnFY+aOMXbGvtDGIolHx5zTKdJzS8c9cX7t2hr1+7u0sW5GMKz8JEctAlFTshnukY2GEfpCHCbUcnYwHPm50uHfRKJMXd8IMew7f2vKgEvT/LaqmJd2w61NxVUbslBlsE2aUR7/pNsN8NWLFFbvY+BMeA/1Mh0dCd0KxP54/CsSI=
      app: ci-me-please-app
      on:
        repo: crmejiam/ci-me-please
        all_branches: true
  - stage: Build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ci-me-please .
    - docker images
    - docker tag ci-me-please $DOCKER_USERNAME/ci-me-please
    - docker push $DOCKER_USERNAME/ci-me-please
  - stage: Test docker image
    script: docker run --rm $DOCKER_USERNAME/ci-me-please
notifications:
  slack:
    secure: aR8fi2vtSuFQ0uDeC7iQzUkuXosXGuYaEB23cBtqkRrCYfm7r6I5T8Gygd7C8kZukvYiiuZd2MdWn7DAyQWW+ptpwQwevzUeUt8HuQb3YT3YznZAiDjmLkEnTBk6l0glvR519SVNlIfu8ocGGY1fk+TdCSoUs/deR/F01idUBaqYTfQRsvWngzpAcc43hDyMpB0eqYvfKVYkt+gJY10Jj/o4UluW7p86MlxhZWmVybqGQrIsikq2BDTuiZcQbYxSPruArTt+D4/33qXjFPpM2+BweLSAhvSdny8iaERa2eLu86rK2wcJbAKoWFQbXnooAAJwS/G08zGJFjCGKSPAHdEgmqSWx0wHgDkq/rtaf0P5DQpjA98OWlNrDoxXH+2czLDj0Zfg8Vr+uJ6WXv/QqN7KGRcyGpPzeqYTEIrLXddT0vWQnKppKPpa7vBz0xRaCL2m1phESsycuI87v1Q+2QZXYJWNIqbAMQYJc/lingWiKUDOGpYur9kG+BRaDVCNslBuoypkoZ3+L05R5iGBJnk2eVhZFUahWCwhw/dcn3+8DvJsbS1Noftd5WslaYes56sjgdf/of1VDwKMLXWCFCxBld687tdL7ThUJIhi5KZEdd8RMkNtSfZiK+zOykYSRyBS8jXHtm1j9Uin/toHOLqjysHE+yalBcPB5tsnSa8=
  email: false
services:
- docker
after_success:
- echo 'Yay! Success!'
after_failure:
- echo 'Damn... Failure'
